### ISSUE TITLE
A500 Plus version possible?

### ISSUE THREAD

**Issue by snz138** [LIV2/A500-2Meg-Chip-ram#2]
Would it be possible to have a version of this board that works in A500+ (in fact A500++) motherboard?

This would be extremely useful when repairing an A500 Plus with the Rob Taylor's A500++ board.
I found your "Diet-Agnus-A500-plus" via his Tindie DIY projects page, but it is "only" 1MB and I have of course the 8375 Agnus.

I would like to keep my A500 Plus motherboard untouched and having RAM in a board like this seems very nice indeed.

I love soldering stuff, but I can't design these thing and I don't think I have the years left anymore to learn :)

**Comment by LIV2** [comment]
Hi @nsxsn 

Unfortunately I don't have the time to work on this life gets in the way!

There are other options though, like Kai Robinson's DRAM board here: https://github.com/kr239/A500-DRAM-Board

**Comment by snz138** [comment]
Thank you for your reply!

I hope one day you will have time (then again I have no idea how big a task it is) :)

Actually I have built that Kai Robinsson's DRAM board, but my A500++ repair build is not far enough to test it yet.

I just thought your Agnus implementation is very nice and compact.

I'll close this issue :)
