### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by bit-image** [LIV2/A500-2Meg-Chip-ram#3]
I installed this board into an A2000 Rev 6.2 and now I only see a black screen, even with DiagRom. I am using this with a 390544-01 in PAL mode. Any assistance would be appreciated. A20 is connected to pin48 on the CPU.

**Comment by LinuxJedi** [comment]
This basically means the board can't talk to Agnus properly. You don't need to hook up the A20 line to test, it will just show 1MB RAM instead of 2MB.

First obvious thing is to check the orientation is correct.

Check the soldering for U4 as that handles the clock (you can also check the 7M clock output to the CPU with a scope). Then check the soldering for Agnus pins / socket for bad joins / shorts.

Also, check the power light on the Amiga comes on (indication of a 5v / GND short if it doesn't).

**Comment by LIV2** [comment]
Pretty much what @LinuxJedi said :) It would also be helpful to see some photos of the bottom of the adapter clearly showing the orientation of U4

**Comment by bit-image** [comment]
Thanks for the assistance, please see photos enclosed. Orientation of U4 appears correct, however the righting on the chip is hard to make out.

![IMG_20220325_084720](https://user-images.githubusercontent.com/102326370/160133193-ff35b68a-6bf9-4bbc-b05b-d64178c1d35d.jpg)
![IMG_20220325_084704](https://user-images.githubusercontent.com/102326370/160133512-8c7ce887-3852-4e58-a8f7-d56b5e26e999.jpg)

**Comment by manmax1** [comment]
Hello ! I am the one that built the meg-chip.
First, this one has been tested and running fine, so I don't know what is happening. Maybe issue with bottom pins, as you know we can apply little amount of solder, and maybe during shipping something broke a solder joint.....I really don't know.  I am scared by my joint with this good zoom :) but I I really checked continuity 2 or 3 times on each components to avoid problems. If we can't solve this I will build a new one for bit-image.  Maybe we can try to bypass u4 by setting the jumper to 28m ? It removes a potential chip fail ?

**Comment by bit-image** [comment]
I set the jumper to 28M, no change. I do not have a scope to test 7M

**Comment by LIV2** [comment]
It may be possible to test if it's a motherboard soldering issue without having to desolder the headers by pushing some [machined pin sockets](https://www.amazon.com/ZYAMY-2-54mm-Female-Straight-Connector/dp/B0778TFL39) into the sockets on the motherboard then you plug a PLCC socket in top of that (making sure to correctly orientate the socket) and finally plug the original Agnus into that and test.

This may not work if the female headers you used are too tall, but it does work for the ones I used & listed in the readme

**Comment by bit-image** [comment]
I've already tested the connectivity of the soldered motherboard headers with my meter.

**Comment by LIV2** [comment]
It could be a bad solder joint on the adapter then perhaps it is worth reflowing the pins, socket and the bottom ics.
Even if the ram had a bad joint the system should partially boot diagrom

**Comment by LIV2** [comment]
Closing because there have been no updates, reopen if needed
