### ISSUE TITLE
Orientation in a Amiga 500 Rev5

### ISSUE THREAD

**Issue by mamejay** [LIV2/A500-2Meg-Chip-ram#4]
Hi Team,
Could be a silly question.  All screenshots I see the 2meg adapter mounted horizontally.
With my motherboard, pin 1 face down and not to the right of the socket..  So would that mean I mount the adapter vertically?
Just want to make sure as pictures from https://bigbookofamigahardware.com/bboah/media/download_photos/a500mb_rev5_3.jpg
show that pin one is down but the agnus in this screenshot is facing to the right.  My Amiga has the Angus mounted with pin 1 down.
Hope this makes sense.

**Comment by LIV2** [comment]
Hi,

Yes on rev 3 & 5 A500's pin one faces the front of the Amiga, so on these revisions it needs to be mounted with pin 1 pointing towards the front
