### ISSUE TITLE
Black Screen - PLCC version

### ISSUE THREAD

**Issue by mamejay** [LIV2/A500-2Meg-Chip-ram#6]
Hi Team,
I have made up a few boards using the PLCC method.  I now get a black screen and diagrom fails to start.
I am using Diagrom VIA a Pistorm which normally gives me serial output on screen but it just hangs.
I am using a Rev5 board which has pin one of the Agnus pointing down.
Only thing I have different on my boards is that I have not install the 74AHCT158 multiplexer and just connected 28M jumper.
Could this have something to do with it?  I have now ordered some HCT158 chips and hope this may sort out the issue.
Any thoughts are welcome.
Thanks

**Comment by LIV2** [comment]
Hi,

I don't think the lack of a multiplexer is causing your problem. Can you please share a photo of one of these adapters top and bottom?

A few questions:
* Which version of Agnus are you using? What is the part number printed on it
* Did you connect A20?
* Did you use the correct part for U3? it needs to be a 74AHC1G08

I would check if Agnus is working + generating the clock signals by probing the clock signals at pins 26,27,28 of Gary for example.

One thing I found when assembling these was that it is very easy to get shorts on the plug side, solder can creep up the legs and cause short circuits so I'd recommend checking closely between the pins
There should only be continuity between the neighboring pins indicated in the red box here:

![image](https://user-images.githubusercontent.com/955874/166149219-7156b475-9766-4ea3-8c3b-e315a500f063.png)

**Comment by mamejay** [comment]
Here are the pictures.  I have tested with A20 connected and not connected as LinuxJedi mentioned that it will still work for testing.
I have the same results with 3 boards and there are no shorts between the socket pins.  I have included the label of the label of the part for 74AHC1G08 I am using from LCSC.
I will check to see if clock is being generated on Gary when I finish work for the day.

![20220502_101956](https://user-images.githubusercontent.com/24428736/166171874-988696bf-d8eb-4bca-b5ce-2aba7b3c1b73.jpg)
![20220502_102001](https://user-images.githubusercontent.com/24428736/166171875-846956fc-c285-400b-940b-f26fd33e978b.jpg)
![20220502_102011](https://user-images.githubusercontent.com/24428736/166171877-2af39a2e-f8a9-48b8-bce2-415cec128121.jpg)
![20220502_101944](https://user-images.githubusercontent.com/24428736/166171879-ddc0d71c-b285-47ff-81c0-91add5c0705d.jpg)
![20220502_101951](https://user-images.githubusercontent.com/24428736/166171881-b9ce93b3-71c3-4bc7-b192-99cb7949420e.jpg)
![20220502_104727](https://user-images.githubusercontent.com/24428736/166172041-72fd9ad4-355d-46f3-aa28-b0d781a4c4df.jpg)

**Comment by LIV2** [comment]
Maybe try removing C6, perhaps it is causing issues on the clock signal for some reason.

Other than that it is a passive adapter so there isn't much to go wrong besides shorts between the pins or bad contact with the socket. 
Even if there's an issue with the ram chip or the single gate IC you should get some diagrom serial output on Pistorm.

**Comment by mamejay** [comment]
Success!! I started checking continuity of the pins on the PLCC socket and found a couple of my boards had bridges.  Could not see them at all so you are correct they are underneath.  As I made 5 boards just in case I tested another that had no bridges and it fired up.
One question.  What is the advantage of using the 74AHCT158 as opposed to not?  Is it better?
I have them on order either way.

PS: Disregard my Frankenstein machine.  I have a HDMI switcher mounted inside my case for a single HDMI output for Pistorm and RGB2HDMI

![20220502_212401](https://user-images.githubusercontent.com/24428736/166227066-4c03c5d3-f730-4307-9f20-93d09c91e424.jpg)
![20220502_212406](https://user-images.githubusercontent.com/24428736/166227079-78074298-ccce-4c41-bb5a-6f9fedc35f46.jpg)

**Comment by LIV2** [comment]
Great stuff :)

The '158 is there to allow use with Genlocks which supply their own 28MHz clock - Earlier models of Agnus had this feature built in but with the 2MB one Commodore removed that feature so it had to be done with external logic.

Not many people are going to need that functionality these days so there's no huge need to fit the 158
