### ISSUE TITLE
Amiga 1000 Rejuvenator

### ISSUE THREAD

**Issue by Ed82** [LIV2/A500-2Meg-Chip-ram#7]
Any idea where to connect A20 when using on a Rejuvenator Board in an Amiga 1000, other than CPU Pin 48, to use 2MB ChipMem? Works fine without A20 connected and 1MB ChipMem or with A20 connected with CPU Pin 48 and 2MB ChipMem.

Thx in advance

**Comment by LIV2** [comment]
Hi @Ed82,

I took a look at the Rejuvinator schematics and it looks like you can get A20 from pin 15 of U28 on the rejuvinator itself

**Comment by Ed82** [comment]
Hello @LIV2,

thx for the answer. I tested it and it works. You can update the Readme.md if you want to.
