### ISSUE TITLE
Substitute for 74AHCT158

### ISSUE THREAD

**Issue by mamejay** [LIV2/A500-2Meg-Chip-ram#8]
Hello everyone.  I have tried to grab parts for a small batch of these and found that 74AHCT158 is near impossible to get my hands on.
Seems to be out of stock.  Is there are substitute for this chip that can be used?

Thanks

**Comment by LIV2** [comment]
Sorry for the late reply @mamejay I somehow missed the notification for this.

You can also use 74AHCT157, 74HCT257 or even better if you're never going to use a genlock you can just leave out U4 and set J1 to "28M"
