### ISSUE TITLE
Agnus Revisions?

### ISSUE THREAD

**Issue by rittwage** [LIV2/A500-2Meg-Chip-ram#9]
I have an 318069-19 which is a late-model NTSC Agnus from an Amiga 3000. It is my understanding that these have a different pinout from the Agnus chips from the A600/A500+ and are replacements for the old 8372B and 8372AB.

I just get a black screen, so it does not work... 

Is there a list of known working Agnus revisions?

**Comment by LIV2** [comment]
Hi @rittwage,

I haven't compiled a list of parts confirmed working with this but I believe any A500+/A600 Agnus should work fine. 

There's a list of part numbers and descriptions [Here](https://bigbookofamigahardware.com/bboah/product.aspx?id=1478) any 2MB A500+/A600 model

**Comment by CCKMik** [comment]
will this adapter work with agnus
 from a500 rev 3/5 ?

**Comment by LIV2** [comment]
@CCKMik no, it is only compatible with the Agnus from the A500+ and A600.

If you have an Agnus from a Rev 3 or 5 and wish to use it in a 500+ you can use the [Diet Agnus](https://github.com/LIV2/Diet-Agnus-A500-plus/) adapter.
